language: cpp
sudo: false
dist: bionic

compiler:
- gcc

os:
- linux

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-regex-dev

before_install:
- gcc --version

script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./build; fi

branches:
   only:
   - master
   - "/^v\\d+\\./"

env:
   global:
   - AX_VERSION="1.3.1"

