language: cpp
sudo: false
dist: bionic

compiler:
- gcc

os:
- linux

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-regex-dev

install:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi

script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./build WITH_TESTS=ON; fi

branches:
   only:
   - master
   - "/^v\\d+\\./"

